jobs:
- job: CPU
  timeoutInMinutes: 0
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - bash: |
     docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
     cd onnxruntime-agent/dockerfiles
     make docker_build_cpu
     ./push.sh docker_push_cpu
- job: GPU
  timeoutInMinutes: 0
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - bash: |
     docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
     cd onnxruntime-agent/dockerfiles
     make docker_build_gpu
     ./push.sh docker_push_gpu
